routes = [
	{ src: "/auth/login", noAuth: true },
	{ src: "/common/attachs" },
	{ src: "/common/types" },
	{ src: "/common/type", path: "/types/:dataId" },
	{ src: "/common/events" },
	{ src: "/auth/password" },
	{ src: "/auth/groups" },
	{ src: "/auth/group", path: "/groups/:dataId" },
	{ src: "/auth/users" },
	{ src: "/auth/user", path: "/users/:dataId" },
	{ src: "/auth/menus" },
	{ src: "/auth/acls" },
	{ src: "/auth/acl", path: "/acls/:dataId" },
	{ src: "/pages/accounts"},
	{ src: "/pages/account", path: "/sites/:dataId" },
	{ src: "/pages/sites"},
	{ src: "/pages/site", path: "/sites/:dataId" },
	{ src: "/pages/occupieds"},
	{ src: "/pages/stores"},
	{ src: "/pages/pcs"},
	{ path: "*", redirect: "/occupieds" },
]