CREATE TABLE OC_ACCOUNT
(
  ID             VARCHAR2(100 BYTE),
  NAME           VARCHAR2(200 BYTE),
  USER_ID        VARCHAR2(100 BYTE),
  USER_PASSWORD  VARCHAR2(100 BYTE),
  SITE_ID        VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE OC_ACL
(
  ID                  VARCHAR2(50 BYTE)         NOT NULL,
  NAME                VARCHAR2(200 BYTE),
  ADMIN_PERMIT        VARCHAR2(50 BYTE),
  OWNER_PERMIT        VARCHAR2(50 BYTE),
  GROUP_PERMIT        VARCHAR2(50 BYTE),
  OTHER_PERMIT        VARCHAR2(50 BYTE),
  GUEST_PERMIT        VARCHAR2(50 BYTE),
  USE_YN              CHAR(1 BYTE)              DEFAULT 'y'                   NOT NULL,
  REG_DATE            DATE,
  REG_USER_ID         VARCHAR2(50 BYTE),
  MOD_DATE            DATE,
  MOD_USER_ID         VARCHAR2(50 BYTE),
  OWNER_GROUP_PERMIT  VARCHAR2(50 BYTE)         DEFAULT 1
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_ACL IS '권한';

COMMENT ON COLUMN OC_ACL.ID IS 'ID';

COMMENT ON COLUMN OC_ACL.NAME IS '이름';

COMMENT ON COLUMN OC_ACL.ADMIN_PERMIT IS '관리자 권한';

COMMENT ON COLUMN OC_ACL.OWNER_PERMIT IS '담당자 권한';

COMMENT ON COLUMN OC_ACL.GROUP_PERMIT IS '부서 권한';

COMMENT ON COLUMN OC_ACL.OTHER_PERMIT IS '기타 권한';

COMMENT ON COLUMN OC_ACL.USE_YN IS '사용 여부';

COMMENT ON COLUMN OC_ACL.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_ACL.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_ACL.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_ACL.MOD_USER_ID IS '등록자';



CREATE TABLE OC_ACL_TYPE
(
  ACL_ID              VARCHAR2(50 BYTE)         NOT NULL,
  TYPE_ID             VARCHAR2(50 BYTE)         NOT NULL,
  ADMIN_PERMIT        VARCHAR2(50 BYTE),
  OWNER_PERMIT        VARCHAR2(50 BYTE),
  GROUP_PERMIT        VARCHAR2(50 BYTE),
  OTHER_PERMIT        VARCHAR2(50 BYTE),
  GUEST_PERMIT        VARCHAR2(50 BYTE),
  OWNER_GROUP_PERMIT  VARCHAR2(50 BYTE)         DEFAULT 1
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_ACL_TYPE IS '권한 항목';

COMMENT ON COLUMN OC_ACL_TYPE.ACL_ID IS 'ID';

COMMENT ON COLUMN OC_ACL_TYPE.TYPE_ID IS 'ID';

COMMENT ON COLUMN OC_ACL_TYPE.ADMIN_PERMIT IS '관리자 권한';

COMMENT ON COLUMN OC_ACL_TYPE.OWNER_PERMIT IS '담당자 권한';

COMMENT ON COLUMN OC_ACL_TYPE.GROUP_PERMIT IS '부서 권한';

COMMENT ON COLUMN OC_ACL_TYPE.OTHER_PERMIT IS '기타 권한';



CREATE TABLE OC_ATTACH
(
  ID            VARCHAR2(50 BYTE)               NOT NULL,
  TARGET_TYPE   VARCHAR2(50 BYTE)               NOT NULL,
  TARGET_ID     VARCHAR2(50 BYTE)               NOT NULL,
  NAME          VARCHAR2(200 BYTE),
  FILE_SIZE     NUMBER,
  REG_DATE      DATE,
  REG_USER_ID   VARCHAR2(50 BYTE),
  CONTENT_TYPE  VARCHAR2(200 BYTE),
  OWNER_ID      VARCHAR2(50 BYTE),
  GROUP_ID      VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_ATTACH IS '첨부';

COMMENT ON COLUMN OC_ATTACH.ID IS 'ID';

COMMENT ON COLUMN OC_ATTACH.TARGET_TYPE IS '엔티티 유형';

COMMENT ON COLUMN OC_ATTACH.TARGET_ID IS '엔티티 ID';

COMMENT ON COLUMN OC_ATTACH.NAME IS '파일명';

COMMENT ON COLUMN OC_ATTACH.FILE_SIZE IS '파일 사이즈';

COMMENT ON COLUMN OC_ATTACH.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_ATTACH.REG_USER_ID IS '등록자';



CREATE TABLE OC_CODE
(
  TYPE_ID      VARCHAR2(50 BYTE)                NOT NULL,
  CODE         VARCHAR2(50 BYTE)                NOT NULL,
  PARENT_CODE  VARCHAR2(50 BYTE),
  NAME         VARCHAR2(200 BYTE),
  VAL_1        VARCHAR2(200 BYTE),
  VAL_2        VARCHAR2(200 BYTE),
  VAL_3        VARCHAR2(200 BYTE),
  VAL_4        VARCHAR2(200 BYTE),
  VAL_5        VARCHAR2(200 BYTE),
  VAL_6        VARCHAR2(200 BYTE),
  VAL_7        VARCHAR2(200 BYTE),
  VAL_8        VARCHAR2(200 BYTE),
  SEQ          NUMBER,
  USE_YN       CHAR(1 BYTE)                     DEFAULT 'y'                   NOT NULL,
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE),
  MOD_DATE     DATE,
  MOD_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_CODE IS '코드';

COMMENT ON COLUMN OC_CODE.TYPE_ID IS '유형 ID';

COMMENT ON COLUMN OC_CODE.CODE IS '코드';

COMMENT ON COLUMN OC_CODE.PARENT_CODE IS '부모 코드';

COMMENT ON COLUMN OC_CODE.NAME IS '이름';

COMMENT ON COLUMN OC_CODE.VAL_1 IS '값 1';

COMMENT ON COLUMN OC_CODE.VAL_2 IS '값 2';

COMMENT ON COLUMN OC_CODE.VAL_3 IS '값 3';

COMMENT ON COLUMN OC_CODE.VAL_4 IS '값 4';

COMMENT ON COLUMN OC_CODE.VAL_5 IS '값 5';

COMMENT ON COLUMN OC_CODE.VAL_6 IS '값 6';

COMMENT ON COLUMN OC_CODE.VAL_7 IS '값 7';

COMMENT ON COLUMN OC_CODE.VAL_8 IS '값 8';

COMMENT ON COLUMN OC_CODE.SEQ IS '순서';

COMMENT ON COLUMN OC_CODE.USE_YN IS '사용 여부';

COMMENT ON COLUMN OC_CODE.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_CODE.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_CODE.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_CODE.MOD_USER_ID IS '등록자';



CREATE TABLE OC_COLUMN
(
  TYPE_ID           VARCHAR2(50 BYTE)           NOT NULL,
  COLUMN_ID         VARCHAR2(50 BYTE)           NOT NULL,
  NAME              VARCHAR2(200 BYTE),
  COLUMN_TYPE       VARCHAR2(50 BYTE),
  COLUMN_RESOURCE   VARCHAR2(200 BYTE),
  EDITOR_OPTIONS    VARCHAR2(4000 BYTE),
  VALUE_FIELD       VARCHAR2(200 BYTE),
  DISPLAY_FIELD     VARCHAR2(200 BYTE),
  VALIDATION_RULES  VARCHAR2(200 BYTE),
  SEQ               NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_COLUMN IS '컬럼';

COMMENT ON COLUMN OC_COLUMN.TYPE_ID IS '유형 ID';

COMMENT ON COLUMN OC_COLUMN.COLUMN_ID IS '컬럼_ID';

COMMENT ON COLUMN OC_COLUMN.NAME IS '이름';

COMMENT ON COLUMN OC_COLUMN.COLUMN_TYPE IS '데이터 유형';

COMMENT ON COLUMN OC_COLUMN.COLUMN_RESOURCE IS '컬럼 리소스';

COMMENT ON COLUMN OC_COLUMN.EDITOR_OPTIONS IS '편집기 옵션';

COMMENT ON COLUMN OC_COLUMN.VALUE_FIELD IS '값 필드';

COMMENT ON COLUMN OC_COLUMN.DISPLAY_FIELD IS '표시 필드';

COMMENT ON COLUMN OC_COLUMN.VALIDATION_RULES IS '유효성 규칙';

COMMENT ON COLUMN OC_COLUMN.SEQ IS '순서';



CREATE TABLE OC_COMMENT
(
  ID           VARCHAR2(50 BYTE)                NOT NULL,
  TYPE_ID      VARCHAR2(50 BYTE),
  ENTITY_ID    VARCHAR2(50 BYTE),
  PARENT_ID    VARCHAR2(50 BYTE),
  "COMMENT"    VARCHAR2(4000 BYTE),
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE),
  MOD_DATE     DATE,
  MOD_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_COMMENT IS '코멘트';

COMMENT ON COLUMN OC_COMMENT.ID IS 'ID';

COMMENT ON COLUMN OC_COMMENT.TYPE_ID IS 'ID';

COMMENT ON COLUMN OC_COMMENT.ENTITY_ID IS '엔티티 ID';

COMMENT ON COLUMN OC_COMMENT.PARENT_ID IS '부모 ID';

COMMENT ON COLUMN OC_COMMENT."COMMENT" IS '코멘트';

COMMENT ON COLUMN OC_COMMENT.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_COMMENT.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_COMMENT.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_COMMENT.MOD_USER_ID IS '등록자';



CREATE TABLE OC_DATASOURCE
(
  ID           VARCHAR2(50 BYTE)                NOT NULL,
  NAME         VARCHAR2(200 BYTE),
  DRIVER       VARCHAR2(200 BYTE),
  URL          VARCHAR2(200 BYTE),
  DIALECT      VARCHAR2(200 BYTE),
  USERNAME     VARCHAR2(200 BYTE),
  PASSWORD     VARCHAR2(200 BYTE),
  INIT_SQL     VARCHAR2(4000 BYTE),
  OWNER_ID     VARCHAR2(50 BYTE),
  GROUP_ID     VARCHAR2(50 BYTE),
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE),
  MOD_DATE     DATE,
  MOD_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_DATASOURCE IS '데이터소스';

COMMENT ON COLUMN OC_DATASOURCE.ID IS 'ID';

COMMENT ON COLUMN OC_DATASOURCE.PASSWORD IS '부모 ID';

COMMENT ON COLUMN OC_DATASOURCE.OWNER_ID IS '부모 ID';

COMMENT ON COLUMN OC_DATASOURCE.GROUP_ID IS '그룹 ID';

COMMENT ON COLUMN OC_DATASOURCE.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_DATASOURCE.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_DATASOURCE.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_DATASOURCE.MOD_USER_ID IS '등록자';



CREATE TABLE OC_GRID_STATE
(
  ID           VARCHAR2(200 BYTE)               NOT NULL,
  FILENAME     VARCHAR2(200 BYTE),
  OWNER_ID     VARCHAR2(50 BYTE),
  GROUP_ID     VARCHAR2(50 BYTE),
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE),
  MOD_DATE     DATE,
  MOD_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OC_GRID_STATE.OWNER_ID IS '작업자 ID';

COMMENT ON COLUMN OC_GRID_STATE.GROUP_ID IS '담당부서 ID';

COMMENT ON COLUMN OC_GRID_STATE.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_GRID_STATE.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_GRID_STATE.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_GRID_STATE.MOD_USER_ID IS '등록자';



CREATE TABLE OC_GROUP
(
  ID              VARCHAR2(50 BYTE)             NOT NULL,
  NAME            VARCHAR2(200 BYTE),
  GROUP_TYPE      VARCHAR2(50 BYTE),
  GROUP_STATUS    VARCHAR2(50 BYTE),
  GROUP_ENG_NAME  VARCHAR2(200 BYTE),
  GROUP_ORDER     VARCHAR2(50 BYTE),
  MANAGER_ID      VARCHAR2(50 BYTE),
  PARENT_ID       VARCHAR2(50 BYTE),
  LOCALE          VARCHAR2(50 BYTE),
  TIMEZONE        VARCHAR2(50 BYTE),
  MEMBER_COUNT    NUMBER,
  REG_DATE        DATE,
  REG_USER_ID     VARCHAR2(50 BYTE),
  MOD_DATE        DATE,
  MOD_USER_ID     VARCHAR2(50 BYTE),
  COMP_CODE       VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_GROUP IS '그룹';

COMMENT ON COLUMN OC_GROUP.ID IS 'ID';

COMMENT ON COLUMN OC_GROUP.NAME IS '이름';

COMMENT ON COLUMN OC_GROUP.GROUP_TYPE IS '그룹 타입';

COMMENT ON COLUMN OC_GROUP.GROUP_STATUS IS '그룹 상태';

COMMENT ON COLUMN OC_GROUP.LOCALE IS '로케일';

COMMENT ON COLUMN OC_GROUP.TIMEZONE IS '타임존';

COMMENT ON COLUMN OC_GROUP.MEMBER_COUNT IS '멤버 수';

COMMENT ON COLUMN OC_GROUP.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_GROUP.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_GROUP.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_GROUP.MOD_USER_ID IS '등록자';



CREATE TABLE OC_MENU
(
  ID           VARCHAR2(50 BYTE)                NOT NULL,
  NAME         VARCHAR2(200 BYTE),
  MENU_TYPE    VARCHAR2(50 BYTE),
  PARENT_ID    VARCHAR2(50 BYTE),
  ICON         VARCHAR2(200 BYTE),
  PATH         VARCHAR2(200 BYTE),
  SEQ          NUMBER,
  USE_YN       CHAR(1 BYTE)                     DEFAULT 'y'                   NOT NULL,
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE),
  MOD_DATE     DATE,
  MOD_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_MENU IS '메뉴';

COMMENT ON COLUMN OC_MENU.ID IS 'ID';

COMMENT ON COLUMN OC_MENU.NAME IS '이름';

COMMENT ON COLUMN OC_MENU.MENU_TYPE IS '주기 유형';

COMMENT ON COLUMN OC_MENU.PARENT_ID IS 'ID';

COMMENT ON COLUMN OC_MENU.ICON IS '아이콘';

COMMENT ON COLUMN OC_MENU.PATH IS '경로';

COMMENT ON COLUMN OC_MENU.SEQ IS '순서';

COMMENT ON COLUMN OC_MENU.USE_YN IS '사용 여부';

COMMENT ON COLUMN OC_MENU.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_MENU.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_MENU.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_MENU.MOD_USER_ID IS '등록자';



CREATE TABLE OC_MENU_GROUP
(
  MENU_ID   VARCHAR2(50 BYTE),
  GROUP_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OC_MENU_GROUP.MENU_ID IS 'ID';

COMMENT ON COLUMN OC_MENU_GROUP.GROUP_ID IS 'ID';



CREATE TABLE OC_MENU_PERM
(
  MENU_ID      VARCHAR2(50 BYTE),
  USER_ID      VARCHAR2(50 BYTE),
  GROUP_ID     VARCHAR2(50 BYTE),
  PERM_TYPE    VARCHAR2(50 BYTE),
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_MENU_PERM IS '?? ??';

COMMENT ON COLUMN OC_MENU_PERM.MENU_ID IS 'ID';

COMMENT ON COLUMN OC_MENU_PERM.USER_ID IS 'ID';

COMMENT ON COLUMN OC_MENU_PERM.GROUP_ID IS 'ID';

COMMENT ON COLUMN OC_MENU_PERM.PERM_TYPE IS '?? ??';

COMMENT ON COLUMN OC_MENU_PERM.REG_DATE IS '?? ??';

COMMENT ON COLUMN OC_MENU_PERM.REG_USER_ID IS '???';



CREATE TABLE OC_MESSAGE
(
  LOCALE       VARCHAR2(50 BYTE)                NOT NULL,
  NAME         VARCHAR2(200 BYTE)               NOT NULL,
  MESSAGE      VARCHAR2(4000 BYTE),
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE),
  MOD_DATE     DATE,
  MOD_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_MESSAGE IS '메세지';

COMMENT ON COLUMN OC_MESSAGE.LOCALE IS '로케일';

COMMENT ON COLUMN OC_MESSAGE.NAME IS '이름';

COMMENT ON COLUMN OC_MESSAGE.MESSAGE IS '메시지';

COMMENT ON COLUMN OC_MESSAGE.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_MESSAGE.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_MESSAGE.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_MESSAGE.MOD_USER_ID IS '등록자';



CREATE TABLE OC_PROP
(
  TYPE_ID           VARCHAR2(50 BYTE)           NOT NULL,
  PROP_ID           VARCHAR2(50 BYTE)           NOT NULL,
  NAME              VARCHAR2(200 BYTE),
  PROP_TYPE         VARCHAR2(50 BYTE),
  PROP_TYPE_ID      VARCHAR2(200 BYTE),
  LIST_VALUE        VARCHAR2(4000 BYTE),
  OPTIONS           VARCHAR2(4000 BYTE),
  VALUE_FIELD       VARCHAR2(200 BYTE),
  DISPLAY_FIELD     VARCHAR2(200 BYTE),
  VALIDATION_RULES  VARCHAR2(200 BYTE),
  WIDTH             NUMBER,
  SEQ               NUMBER,
  USE_YN            NUMBER                      NOT NULL,
  COL_SPAN          NUMBER                      DEFAULT 1,
  REQUIRED          NUMBER                      DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE OC_RESOURCE
(
  ID             VARCHAR2(50 BYTE)              NOT NULL,
  NAME           VARCHAR2(200 BYTE),
  DATASOURCE_ID  VARCHAR2(50 BYTE),
  TABLE_NAME     VARCHAR2(200 BYTE),
  OWNER_ID       VARCHAR2(50 BYTE),
  GROUP_ID       VARCHAR2(50 BYTE),
  REG_DATE       DATE,
  REG_USER_ID    VARCHAR2(50 BYTE),
  MOD_DATE       DATE,
  MOD_USER_ID    VARCHAR2(50 BYTE),
  OPTIONS        VARCHAR2(4000 BYTE),
  PK             VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_RESOURCE IS '리소스';

COMMENT ON COLUMN OC_RESOURCE.ID IS 'ID';

COMMENT ON COLUMN OC_RESOURCE.OWNER_ID IS '부모 ID';

COMMENT ON COLUMN OC_RESOURCE.GROUP_ID IS '그룹 ID';

COMMENT ON COLUMN OC_RESOURCE.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_RESOURCE.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_RESOURCE.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_RESOURCE.MOD_USER_ID IS '등록자';



CREATE TABLE OC_SITE
(
  ID           VARCHAR2(100 BYTE),
  NAME         VARCHAR2(100 BYTE),
  LOGIN_URL    VARCHAR2(1000 BYTE),
  ID_XPATH     VARCHAR2(500 BYTE),
  PW_XPATH     VARCHAR2(500 BYTE),
  LOGIN_XPATH  VARCHAR2(500 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE OC_TYPE
(
  ID           VARCHAR2(50 BYTE)                NOT NULL,
  NAME         VARCHAR2(50 BYTE)                NOT NULL,
  TYPE_CAT     VARCHAR2(50 BYTE)                NOT NULL,
  SEQ          NUMBER,
  USE_YN       CHAR(1 BYTE)                     DEFAULT 'y'                   NOT NULL,
  REG_DATE     DATE,
  REG_USER_ID  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_TYPE IS '타입';

COMMENT ON COLUMN OC_TYPE.ID IS 'ID';

COMMENT ON COLUMN OC_TYPE.NAME IS '이름';

COMMENT ON COLUMN OC_TYPE.SEQ IS '순서';

COMMENT ON COLUMN OC_TYPE.USE_YN IS '사용 여부';

COMMENT ON COLUMN OC_TYPE.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_TYPE.REG_USER_ID IS '등록자';



CREATE TABLE OC_USER
(
  ID                          VARCHAR2(50 BYTE) NOT NULL,
  USER_ID                     VARCHAR2(50 BYTE),
  USER_NAME                   VARCHAR2(200 BYTE),
  USER_ENG_NAME               VARCHAR2(200 BYTE),
  ENCRYPTED_PASSWORD          VARCHAR2(200 BYTE),
  SESSION_ID                  VARCHAR2(200 BYTE),
  GROUP_ID                    VARCHAR2(50 BYTE),
  USER_TYPE                   VARCHAR2(50 BYTE),
  USER_STATUS                 VARCHAR2(50 BYTE),
  EMAIL                       VARCHAR2(200 BYTE),
  LOCALE                      VARCHAR2(50 BYTE),
  TIMEZONE                    VARCHAR2(50 BYTE),
  ACL_ID                      VARCHAR2(50 BYTE),
  REG_DATE                    DATE,
  REG_USER_ID                 VARCHAR2(50 BYTE),
  MOD_DATE                    DATE,
  MOD_USER_ID                 VARCHAR2(50 BYTE),
  PLACE_ID                    VARCHAR2(50 BYTE),
  CHECKLIST_ID                VARCHAR2(50 BYTE),
  NAME                        VARCHAR2(200 BYTE),
  SECURE_KEY                  VARCHAR2(200 BYTE),
  SECURE_KEY_EXPIRATION_DATE  DATE,
  POSITION                    VARCHAR2(50 BYTE),
  LOGIN_FAILURE_COUNT         INTEGER,
  BLOCKED_DATE                DATE,
  EXPIRATION_DATE             DATE,
  PASSWORD_EXPIRATION_DATE    DATE,
  LAST_LOGIN_DATE             DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_USER IS '사용자';

COMMENT ON COLUMN OC_USER.ID IS 'ID';

COMMENT ON COLUMN OC_USER.USER_NAME IS '이름';

COMMENT ON COLUMN OC_USER.ENCRYPTED_PASSWORD IS '비밀번호';

COMMENT ON COLUMN OC_USER.SESSION_ID IS '세션 ID';

COMMENT ON COLUMN OC_USER.GROUP_ID IS '그룹 ID';

COMMENT ON COLUMN OC_USER.USER_TYPE IS '사용자 유형';

COMMENT ON COLUMN OC_USER.USER_STATUS IS '사용자 상태';

COMMENT ON COLUMN OC_USER.LOCALE IS '로케일';

COMMENT ON COLUMN OC_USER.TIMEZONE IS '타임존';

COMMENT ON COLUMN OC_USER.ACL_ID IS '권한 ID';

COMMENT ON COLUMN OC_USER.REG_DATE IS '등록 일시';

COMMENT ON COLUMN OC_USER.REG_USER_ID IS '등록자';

COMMENT ON COLUMN OC_USER.MOD_DATE IS '등록 일시';

COMMENT ON COLUMN OC_USER.MOD_USER_ID IS '등록자';



CREATE INDEX IX_OC_USER_01 ON OC_USER
(GROUP_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX OC_ACCOUNT_PK ON OC_ACCOUNT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX OC_SITE_PK ON OC_SITE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_ATTACH ON OC_ATTACH
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_CODE ON OC_CODE
(TYPE_ID, CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_COLUMN ON OC_COLUMN
(TYPE_ID, COLUMN_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_COMMENT ON OC_COMMENT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_DATASOURCE ON OC_DATASOURCE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_GRID_STATE ON OC_GRID_STATE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_GROUP ON OC_GROUP
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_MENU ON OC_MENU
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_MESSAGE ON OC_MESSAGE
(LOCALE, NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_PERM ON OC_ACL
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_PERM_ITEM ON OC_ACL_TYPE
(ACL_ID, TYPE_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_PROP ON OC_PROP
(TYPE_ID, PROP_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_RESOURCE ON OC_RESOURCE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_TYPE ON OC_TYPE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_USER ON OC_USER
(ID)
LOGGING
NOPARALLEL;


CREATE TABLE OC_EVENT
(
  ID              VARCHAR2(50 BYTE)             NOT NULL,
  REMOTE_ADDR     VARCHAR2(200 BYTE),
  HOST_ADDR       VARCHAR2(200 BYTE),
  REQUEST_URL     VARCHAR2(4000 BYTE),
  REQUEST_METHOD  VARCHAR2(200 BYTE),
  ELAPSED_MS      NUMBER,
  RESOURCE_NAME   VARCHAR2(50 BYTE)             NOT NULL,
  COMMAND_NAME    VARCHAR2(50 BYTE)             NOT NULL,
  DATA_ID         VARCHAR2(50 BYTE),
  CONDITION_VAL   VARCHAR2(4000 BYTE),
  ROW_VAL         VARCHAR2(4000 BYTE),
  RESULT_COUNT    NUMBER,
  OWNER_ID        VARCHAR2(50 BYTE),
  GROUP_ID        VARCHAR2(50 BYTE),
  REG_DATE        DATE,
  NOTE            VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_EVENT IS '이벤트';

COMMENT ON COLUMN OC_EVENT.ID IS 'ID';

COMMENT ON COLUMN OC_EVENT.RESOURCE_NAME IS '엔티티 유형';

COMMENT ON COLUMN OC_EVENT.COMMAND_NAME IS '이벤트 유형';

COMMENT ON COLUMN OC_EVENT.DATA_ID IS '엔티티 ID';

COMMENT ON COLUMN OC_EVENT.ROW_VAL IS '신규 값';

COMMENT ON COLUMN OC_EVENT.OWNER_ID IS '부모 ID';

COMMENT ON COLUMN OC_EVENT.GROUP_ID IS '그룹 ID';

COMMENT ON COLUMN OC_EVENT.REG_DATE IS '등록 일시';



CREATE TABLE OC_GROUP_MEMBER
(
  GROUP_ID     VARCHAR2(50 BYTE)                NOT NULL,
  USER_ID      VARCHAR2(50 BYTE)                NOT NULL,
  MEMBER_TYPE  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OC_GROUP_MEMBER IS '그룹 멤버';

COMMENT ON COLUMN OC_GROUP_MEMBER.GROUP_ID IS '그룹 ID';

COMMENT ON COLUMN OC_GROUP_MEMBER.USER_ID IS '사용자 ID';

COMMENT ON COLUMN OC_GROUP_MEMBER.MEMBER_TYPE IS '멤버 유형';



CREATE INDEX IX_OC_EVENT_01 ON OC_EVENT
(OWNER_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_EVENT ON OC_EVENT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_OC_GROUP_MEMBER ON OC_GROUP_MEMBER
(GROUP_ID, USER_ID)
LOGGING
NOPARALLEL;


ALTER TABLE OC_ACCOUNT ADD (
  CONSTRAINT OC_ACCOUNT_PK
  PRIMARY KEY
  (ID)
  USING INDEX OC_ACCOUNT_PK
  ENABLE VALIDATE);

ALTER TABLE OC_ACL ADD (
  CONSTRAINT PK_OC_PERM
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_PERM
  ENABLE VALIDATE);

ALTER TABLE OC_ACL_TYPE ADD (
  CONSTRAINT PK_OC_PERM_ITEM
  PRIMARY KEY
  (ACL_ID, TYPE_ID)
  USING INDEX PK_OC_PERM_ITEM
  ENABLE VALIDATE);

ALTER TABLE OC_ATTACH ADD (
  CONSTRAINT PK_OC_ATTACH
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_ATTACH
  ENABLE VALIDATE);

ALTER TABLE OC_CODE ADD (
  CONSTRAINT PK_OC_CODE
  PRIMARY KEY
  (TYPE_ID, CODE)
  USING INDEX PK_OC_CODE
  ENABLE VALIDATE);

ALTER TABLE OC_COLUMN ADD (
  CONSTRAINT PK_OC_COLUMN
  PRIMARY KEY
  (TYPE_ID, COLUMN_ID)
  USING INDEX PK_OC_COLUMN
  ENABLE VALIDATE);

ALTER TABLE OC_COMMENT ADD (
  CONSTRAINT PK_OC_COMMENT
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_COMMENT
  ENABLE VALIDATE);

ALTER TABLE OC_DATASOURCE ADD (
  CONSTRAINT PK_OC_DATASOURCE
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_DATASOURCE
  ENABLE VALIDATE);

ALTER TABLE OC_GRID_STATE ADD (
  CONSTRAINT PK_OC_GRID_STATE
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_GRID_STATE
  ENABLE VALIDATE);

ALTER TABLE OC_GROUP ADD (
  CONSTRAINT PK_OC_GROUP
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_GROUP
  ENABLE VALIDATE);

ALTER TABLE OC_MENU ADD (
  CONSTRAINT PK_OC_MENU
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_MENU
  ENABLE VALIDATE);

ALTER TABLE OC_MESSAGE ADD (
  CONSTRAINT PK_OC_MESSAGE
  PRIMARY KEY
  (LOCALE, NAME)
  USING INDEX PK_OC_MESSAGE
  ENABLE VALIDATE);

ALTER TABLE OC_PROP ADD (
  CONSTRAINT PK_OC_PROP
  PRIMARY KEY
  (TYPE_ID, PROP_ID)
  USING INDEX PK_OC_PROP
  ENABLE VALIDATE);

ALTER TABLE OC_RESOURCE ADD (
  CONSTRAINT PK_OC_RESOURCE
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_RESOURCE
  ENABLE VALIDATE);

ALTER TABLE OC_SITE ADD (
  CONSTRAINT OC_SITE_PK
  PRIMARY KEY
  (ID)
  USING INDEX OC_SITE_PK
  ENABLE VALIDATE);

ALTER TABLE OC_TYPE ADD (
  CONSTRAINT PK_OC_TYPE
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_TYPE
  ENABLE VALIDATE);

ALTER TABLE OC_USER ADD (
  CONSTRAINT PK_OC_USER
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_USER
  ENABLE VALIDATE);

ALTER TABLE OC_EVENT ADD (
  CONSTRAINT PK_OC_EVENT
  PRIMARY KEY
  (ID)
  USING INDEX PK_OC_EVENT
  ENABLE VALIDATE);

ALTER TABLE OC_GROUP_MEMBER ADD (
  CONSTRAINT PK_OC_GROUP_MEMBER
  PRIMARY KEY
  (GROUP_ID, USER_ID)
  USING INDEX PK_OC_GROUP_MEMBER
  ENABLE VALIDATE);

ALTER TABLE OC_CODE ADD (
  CONSTRAINT FK_OC_CODE_REFERENCE_OC_CODE 
  FOREIGN KEY (TYPE_ID, PARENT_CODE) 
  REFERENCES OC_CODE (TYPE_ID,CODE)
  ENABLE VALIDATE);

ALTER TABLE OC_COMMENT ADD (
  CONSTRAINT FK_OC_COMME_REFERENCE_OC_COMME 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OC_COMMENT (ID)
  ENABLE VALIDATE);

ALTER TABLE OC_MENU ADD (
  CONSTRAINT FK_OC_MENU_REFERENCE_OC_MENU 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OC_MENU (ID)
  ENABLE VALIDATE);

ALTER TABLE OC_MENU_GROUP ADD (
  CONSTRAINT FK_OC_MENU__REFERENCE_OC_MENU 
  FOREIGN KEY (MENU_ID) 
  REFERENCES OC_MENU (ID)
  ENABLE VALIDATE);

ALTER TABLE OC_USER ADD (
  CONSTRAINT FK_OC_USER_REFERENCE_OC_GROUP 
  FOREIGN KEY (GROUP_ID) 
  REFERENCES OC_GROUP (ID)
  ENABLE VALIDATE);

ALTER TABLE OC_EVENT ADD (
  CONSTRAINT FK_OC_EVENT_REFERENCE_OC_USER 
  FOREIGN KEY (OWNER_ID) 
  REFERENCES OC_USER (ID)
  ENABLE VALIDATE);

ALTER TABLE OC_GROUP_MEMBER ADD (
  CONSTRAINT FK_OC_GROUP_REFERENCE_OC_GROUP 
  FOREIGN KEY (GROUP_ID) 
  REFERENCES OC_GROUP (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_OC_GROUP_REFERENCE_OC_USER 
  FOREIGN KEY (USER_ID) 
  REFERENCES OC_USER (ID)
  ENABLE VALIDATE);
